<a href="https://colab.research.google.com/github/mfagundes/python-ciencia-de-dados/blob/main/misc/Matrix_multiplication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  Multiplicação de matrizes - numpy.dot()

- [Resposta 1 do SO](https://stackoverflow.com/questions/54730082/why-does-numpy-dot-product-of-2d-array-with-1d-array-produce-1d-array)
- [Resposta 2 do SO](https://stackoverflow.com/questions/43232938/np-array-dot-product-of-vector-and-array)

In [1]:
import numpy as np

In [2]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [3]:
B = np.array([2, 4, 6])

In [4]:
B.shape

(3,)

In [5]:
print(A)
print()
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[2 4 6]


In [6]:
A @ B

array([ 28,  64, 100])

In [7]:
A.dot(B)

array([ 28,  64, 100])

In [8]:
A.dot(B).shape

(3,)

In [9]:
C = np.array([28, 64, 100])

In [10]:
C.shape

(3,)

In [11]:
C1 = np.array([[28, 64, 100]])

In [12]:
C1.shape

(1, 3)

In [13]:
A.dot(C)

array([ 456, 1032, 1608])

In [14]:
A.dot(C).shape

(3,)

In [16]:
# this produces an error
A.dot(C1)

ValueError: ignored

In [17]:
C2 = np.array([[28], [64], [100]])

In [18]:
C2.shape

(3, 1)

In [19]:
A.dot(C2)

array([[ 456],
       [1032],
       [1608]])

In [20]:
A.dot(C2).shape

(3, 1)