<a href="https://colab.research.google.com/github/mfagundes/python-ciencia-de-dados/blob/main/100_unidade02_exercicios_enunciados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python para Ciência de Dados
---
---

# Unidade 02 - Exercícios
---

In [86]:
import numpy as np

## Exercício 1

Crie um array 5x5 com a sequência 1...25 (incluso) e faça a soma dos elementos da diagonal.

In [87]:
########################
# Início do seu código #
########################


In [88]:
A = np.array(range(1,26)).reshape(5,5)

In [89]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## Exercício 2

Crie um array 5x5 com a sequência de números pares entre 0...50 (incluso) e faça as seguintes operações:
 1. Soma das linhas
 2. Soma das colunas
 3. Média dos elementos da última linha
 4. Média dos elementos da última coluna

In [ ]:
########################
# Início do seu código #
########################



## Exercício 3

Dado o array 2D a seguir, substitua o seu maior valor por 0.

In [ ]:
import numpy as np
array = np.random.normal(0, 3, size=(5, 5))
print(array)
########################
# Inicio do seu código #
########################



[[ 2.95762462 -2.03597243  5.94232655  0.39238978 -1.95145709]
 [-2.75334665  0.53307347 -1.2079649  -1.35667712  1.85690007]
 [ 9.2205608   4.57430227  0.1136759   3.96259811  2.19731099]
 [ 0.64757833  1.16692083 -0.31765555 -4.09718832  0.24594572]
 [-2.41058108  0.78612364  6.09949888 -3.87238459 -5.54470088]]


## Exercício 4

Dado o par de arrays 2D abaixo, determine se é possível realizar uma multiplicação de matriz, realize a multiplicação caso seja possível.

In [ ]:
a = np.random.uniform(size=(5, 3))
b = np.random.uniform(size=(3, 4))

########################
# Início do seu código #
########################



## Exercício 5

Dado o array abaixo, converta-o para um array do tipo int32.

In [ ]:
a = np.arange(9, dtype=np.float32).reshape(3, 3)

########################
# Início do seu código #
########################



## Exercício 6

Dado o array abaixo, some 10 em todos os elementos da última coluna.

In [ ]:
a = np.random.uniform(size=(8, 8))

########################
# Início do seu código #
########################


## Exercício 7

Crie um array 2D 4x4 de inteiros que possua a seguinte estrutura:

```python
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
```

In [ ]:
########################
# Início do seu código #
########################


## Exercício 8

Dados os dois arrays 2x4 abaixo (`a` e `b`), empilhe os dois formando um novo array 4x4

In [ ]:
a = np.array([[0,3,4,5], [7, 10, 9, 2]])
b = np.array([[1,4,9,12], [15, 22, 19, 17]])
########################
# Início do seu código #
########################


## Exercício 9

Leia o arquivo `actors.csv` e faça o seguintes cálculos sobre o conjunto de dados utilizando **Numpy**:

1. O ator/atriz com maior número de filmes e o respectivo númeo de filmes.
2. A média do número de filmes.
3. O ator/atriz com a maior média por filme.
4. O nome do(s) filme(s) mais frequente(s) e sua respectiva frequência.

Dica: Faça o parsing do arquivo utilizando o pacote [csv](https://docs.python.org/3/library/csv.html) do python e depois converta os dados para array e então realize as operações solicitadas. O [numpy não oferece](https://stackoverflow.com/questions/28444272/numpy-loadtxt-how-to-ignore-comma-delimiters-that-appear-inside-quotes) uma maneira de ler csv que possa lidar com vírgulas que estão entre aspas (").

In [ ]:
#Transferindo arquivo compartilhado como: https://drive.google.com/file/d/11Bgqcm7nqvXjvdb5N3LMgKTRBXquPkRI/view?usp=sharing
!wget !wget https://drive.google.com/uc?id=11Bgqcm7nqvXjvdb5N3LMgKTRBXquPkRI -O actors.csv
!cat actors.csv

In [ ]:
import csv

########################
# Início do seu código #
########################


---