<a href="https://colab.research.google.com/github/mfagundes/python-ciencia-de-dados/blob/main/100_unidade02_exercicios_enunciados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python para Ciência de Dados
---
---

# Unidade 02 - Exercícios
---

In [1]:
import numpy as np

## Exercício 1

Crie um array 5x5 com a sequência 1...25 (incluso) e faça a soma dos elementos da diagonal.

In [2]:
########################
# Início do seu código #
########################


In [3]:
A = np.array(range(1,26)).reshape(5,5)

In [4]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## Exercício 2

Crie um array 5x5 com a sequência de números pares entre 0...50 (incluso) e faça as seguintes operações:
 1. Soma das linhas
 2. Soma das colunas
 3. Média dos elementos da última linha
 4. Média dos elementos da última coluna

In [6]:
########################
# Início do seu código #
########################
B = np.array(range(2, 51, 2)).reshape(5,5)


In [9]:
B

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

In [10]:
#1. Soma das linhas
B.sum(axis=1)

array([ 30,  80, 130, 180, 230])

In [11]:
# 2. Soma das colunas
B.sum(axis=0)

array([110, 120, 130, 140, 150])

In [12]:
# 3. Média dos elementos da última linha
B[-1, :].mean()

46.0

In [13]:
# 4. Média dos lementos a última coluna
B[:, -1].mean()

30.0

## Exercício 3

Dado o array 2D a seguir, substitua o seu maior valor por 0.

In [14]:
import numpy as np
array = np.random.normal(0, 3, size=(5, 5))
print(array)
########################
# Inicio do seu código #
########################



[[ 3.15590062  1.56780765  5.72514834  2.38613302 -1.67915556]
 [ 5.8969024  -3.04756697 -2.33030282 -0.08191739 -0.58294375]
 [-2.65571254 -3.7452956   5.24752983 -1.77933839  3.04436418]
 [ 0.93423072  3.90971949  4.14175071  1.28732659  0.17586671]
 [-4.69328937  1.22634047 -2.34920219  2.39624715  0.16715043]]


In [15]:
array.reshape(-1)[array.argmax()] = 0

In [16]:
array

array([[ 3.15590062,  1.56780765,  5.72514834,  2.38613302, -1.67915556],
       [ 0.        , -3.04756697, -2.33030282, -0.08191739, -0.58294375],
       [-2.65571254, -3.7452956 ,  5.24752983, -1.77933839,  3.04436418],
       [ 0.93423072,  3.90971949,  4.14175071,  1.28732659,  0.17586671],
       [-4.69328937,  1.22634047, -2.34920219,  2.39624715,  0.16715043]])

## Usando ravel e flatten
Ambos fazem transformações semelhantes ao ``reshape(-1)``. O ``ravel``, porém, cria uma view, enquanto ``flatten`` cria uma cópia. Assim, a modificação solicitada do elemento não será feita na matriz principal usando o ``flatten``.

Usando o ``ndarray.base()`` podemos verificar se é uma view. Se for, retornará a matriz original (caso do ``ravel``). Caso contrário (o ``flatten``) retornará ``False``.

In [21]:
# Gerando nova matriz
array2 = np.random.normal(0, 3, size=(5, 5))
print(array2)

[[-1.11781806  0.17748716 -0.67415682  1.09971328 -2.40055105]
 [ 1.13074353 -4.65947881  1.99358857 -5.94301357  7.23599515]
 [ 5.9920986  -4.23311716 -1.49997764 -0.55468932 -0.04078585]
 [ 0.03501991 -1.10006916  1.28514191 -0.85565823  2.6386114 ]
 [ 0.87111348 -0.95250817  6.59294191  3.81058323  0.10937467]]


In [23]:
array2.ravel()[array2.argmax()] = 0

In [24]:
array2

array([[-1.11781806,  0.17748716, -0.67415682,  1.09971328, -2.40055105],
       [ 1.13074353, -4.65947881,  1.99358857, -5.94301357,  0.        ],
       [ 5.9920986 , -4.23311716, -1.49997764, -0.55468932, -0.04078585],
       [ 0.03501991, -1.10006916,  1.28514191, -0.85565823,  2.6386114 ],
       [ 0.87111348, -0.95250817,  6.59294191,  3.81058323,  0.10937467]])

Usando o ``flatten``

In [27]:
array3 = np.random.normal(0, 3, size=(5, 5))
print(array3)

[[-1.29552645  2.78996223  0.70289541 -1.81611412 -2.41855738]
 [ 3.5450403  -1.39850812  0.44567547 -1.41811064 -2.88998184]
 [-3.49194425 -1.26882374 -3.08512386  1.26695557 -0.25539376]
 [ 0.37774037 -3.52141956  3.08845484 -2.47345874 -2.00480984]
 [-2.6965413  -1.63058266 -0.86367645 -0.92689531 -3.41593677]]


In [30]:
array3.flatten()[array3.argmax()] = 0

In [31]:
array3

array([[-1.29552645,  2.78996223,  0.70289541, -1.81611412, -2.41855738],
       [ 3.5450403 , -1.39850812,  0.44567547, -1.41811064, -2.88998184],
       [-3.49194425, -1.26882374, -3.08512386,  1.26695557, -0.25539376],
       [ 0.37774037, -3.52141956,  3.08845484, -2.47345874, -2.00480984],
       [-2.6965413 , -1.63058266, -0.86367645, -0.92689531, -3.41593677]])

Como pode-se notar, o maior valor de ``array3`` não foi alterado

## Verificando bases e ids

In [34]:
X = np.array([[1,2,3], [4,5,6]])
r = X.ravel()
f = X.flatten()

In [43]:
print(id(X), id(r.base), id(f.base))

140051681162608 140051681162608 11125344


Observa-se que o id do ``r.base`` é igual ao da matriz original, enquanto o do ``f.base`` é diferente. Quando se trata de uma ``view``, o id da base é idêntico ao da matriz original. 

Para melhor compreensão, [ver este link do Stack Overflow](https://stackoverflow.com/questions/28930465/what-is-the-difference-between-flatten-and-ravel-functions-in-numpy/54313275#54313275)

In [39]:
print(r.base)

[[1 2 3]
 [4 5 6]]


In [40]:
print(f.base)

None


## Exercício 4

Dado o par de arrays 2D abaixo, determine se é possível realizar uma multiplicação de matriz, realize a multiplicação caso seja possível.

In [15]:
a = np.random.uniform(size=(5, 3))
b = np.random.uniform(size=(3, 4))

########################
# Início do seu código #
########################



In [16]:
c = np.dot(a,b)

In [17]:
c

array([[1.49168656, 0.72893874, 0.98698955, 0.71327867],
       [1.10329776, 0.64808077, 0.59355209, 0.43675377],
       [0.99383525, 0.72365543, 0.5797551 , 0.74113284],
       [1.29033459, 0.96742008, 0.81884689, 1.15196108],
       [1.27285346, 0.97284026, 0.55888595, 0.64530679]])

## Exercício 5

Dado o array abaixo, converta-o para um array do tipo int32.

In [18]:
a = np.arange(9, dtype=np.float32).reshape(3, 3)

########################
# Início do seu código #
########################



In [19]:
a = a.astype('int32')

In [20]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)

## Exercício 6

Dado o array abaixo, some 10 em todos os elementos da última coluna.

In [21]:
a = np.random.uniform(size=(8, 8))

########################
# Início do seu código #
########################


In [22]:
a

array([[0.19973909, 0.23469067, 0.56643377, 0.94261209, 0.49086552,
        0.71184447, 0.48885867, 0.63493962],
       [0.00703913, 0.42777551, 0.65990298, 0.73165754, 0.70633975,
        0.47067639, 0.69895333, 0.58285532],
       [0.19834394, 0.89771333, 0.73897307, 0.88863581, 0.23017024,
        0.17487938, 0.78496926, 0.48215718],
       [0.36316924, 0.13390955, 0.62476985, 0.60270576, 0.4152509 ,
        0.58168609, 0.88897761, 0.32427781],
       [0.39230253, 0.14435665, 0.29939632, 0.92727087, 0.92724775,
        0.04026991, 0.45200201, 0.22384568],
       [0.57615566, 0.1086603 , 0.87065453, 0.82090751, 0.16760297,
        0.26487112, 0.88518613, 0.24483728],
       [0.94452051, 0.42565321, 0.11536461, 0.10413188, 0.08801854,
        0.74358383, 0.31215429, 0.33385677],
       [0.67180924, 0.8545113 , 0.28996976, 0.71873928, 0.30070552,
        0.58806229, 0.56142346, 0.53297109]])

In [23]:
a[:, -1] += 10

In [24]:
a

array([[1.99739093e-01, 2.34690673e-01, 5.66433770e-01, 9.42612085e-01,
        4.90865516e-01, 7.11844473e-01, 4.88858672e-01, 1.06349396e+01],
       [7.03913386e-03, 4.27775506e-01, 6.59902979e-01, 7.31657544e-01,
        7.06339746e-01, 4.70676389e-01, 6.98953332e-01, 1.05828553e+01],
       [1.98343939e-01, 8.97713329e-01, 7.38973069e-01, 8.88635808e-01,
        2.30170240e-01, 1.74879384e-01, 7.84969261e-01, 1.04821572e+01],
       [3.63169242e-01, 1.33909550e-01, 6.24769851e-01, 6.02705760e-01,
        4.15250899e-01, 5.81686094e-01, 8.88977612e-01, 1.03242778e+01],
       [3.92302529e-01, 1.44356655e-01, 2.99396320e-01, 9.27270872e-01,
        9.27247748e-01, 4.02699051e-02, 4.52002013e-01, 1.02238457e+01],
       [5.76155662e-01, 1.08660302e-01, 8.70654526e-01, 8.20907508e-01,
        1.67602965e-01, 2.64871115e-01, 8.85186135e-01, 1.02448373e+01],
       [9.44520515e-01, 4.25653210e-01, 1.15364614e-01, 1.04131880e-01,
        8.80185372e-02, 7.43583831e-01, 3.12154290e-01, 1.

## Exercício 7

Crie um array 2D 4x4 de inteiros que possua a seguinte estrutura:

```python
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
```

In [25]:
########################
# Início do seu código #
########################
D = np.array([np.random.randint(1, 17) for _ in range(1, 17)]).reshape(4,4)

In [26]:
D

array([[15,  3,  9, 11],
       [ 8,  3, 14, 11],
       [ 5, 12,  8,  4],
       [10, 10,  4, 16]])

## Exercício 8

Dados os dois arrays 2x4 abaixo (`a` e `b`), empilhe os dois formando um novo array 4x4

In [27]:
a = np.array([[0,3,4,5], [7, 10, 9, 2]])
b = np.array([[1,4,9,12], [15, 22, 19, 17]])
########################
# Início do seu código #
########################


In [28]:
a

array([[ 0,  3,  4,  5],
       [ 7, 10,  9,  2]])

In [29]:
b

array([[ 1,  4,  9, 12],
       [15, 22, 19, 17]])

In [30]:
c = np.concatenate((a, b))

In [31]:
c

array([[ 0,  3,  4,  5],
       [ 7, 10,  9,  2],
       [ 1,  4,  9, 12],
       [15, 22, 19, 17]])

## Exercício 9

Leia o arquivo `actors.csv` e faça o seguintes cálculos sobre o conjunto de dados utilizando **Numpy**:

1. O ator/atriz com maior número de filmes e o respectivo númeo de filmes.
2. A média do número de filmes.
3. O ator/atriz com a maior média por filme.
4. O nome do(s) filme(s) mais frequente(s) e sua respectiva frequência.

Dica: Faça o parsing do arquivo utilizando o pacote [csv](https://docs.python.org/3/library/csv.html) do python e depois converta os dados para array e então realize as operações solicitadas. O [numpy não oferece](https://stackoverflow.com/questions/28444272/numpy-loadtxt-how-to-ignore-comma-delimiters-that-appear-inside-quotes) uma maneira de ler csv que possa lidar com vírgulas que estão entre aspas (").

In [32]:
#Transferindo arquivo compartilhado como: https://drive.google.com/file/d/11Bgqcm7nqvXjvdb5N3LMgKTRBXquPkRI/view?usp=sharing
!wget !wget https://drive.google.com/uc?id=11Bgqcm7nqvXjvdb5N3LMgKTRBXquPkRI -O actors.csv
!cat actors.csv

--2022-07-09 01:07:49--  http://!wget/
Resolving !wget (!wget)... failed: Name or service not known.
wget: unable to resolve host address ‘!wget’
--2022-07-09 01:07:50--  https://drive.google.com/uc?id=11Bgqcm7nqvXjvdb5N3LMgKTRBXquPkRI
Resolving drive.google.com (drive.google.com)... 142.251.16.139, 142.251.16.100, 142.251.16.101, ...
Connecting to drive.google.com (drive.google.com)|142.251.16.139|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://doc-10-ag-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/cnt3ejjumgoueka3i3c23bn4fjkt47dq/1657328850000/05702288761093373215/*/11Bgqcm7nqvXjvdb5N3LMgKTRBXquPkRI?uuid=fb1c9b13-021a-4d35-9f13-bef180429695 [following]
--2022-07-09 01:07:50--  https://doc-10-ag-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/cnt3ejjumgoueka3i3c23bn4fjkt47dq/1657328850000/05702288761093373215/*/11Bgqcm7nqvXjvdb5N3LMgKTRBXquPkRI?uuid=fb1c9b13-021a-4d35-9f13-bef180429695
Re

Considerei desnecessário parsear com o csv e gerar arrays do Numpy - até porque o professor, neste ponto, passa para o Pandas. Decidi, então, fazer este exercício diretamente no Pandas.

In [33]:
import csv
import pandas as pd


########################
# Início do seu código #
########################

df = pd.read_csv('actors.csv', sep=",")


In [34]:
df.head()

Actor  Total Gross  Number of Movies  Average per Movie  \
0       Harrison Ford       4871.7                41              118.8   
1   Samuel L. Jackson       4772.8                69               69.2   
2      Morgan Freeman       4468.3                61               73.3   
3           Tom Hanks       4340.8                44               98.7   
4  Robert Downey, Jr.       3947.3                53               74.5   

                       #1 Movie  Gross  
0  Star Wars: The Force Awakens  936.7  
1                  The Avengers  623.4  
2               The Dark Knight  534.9  
3                   Toy Story 3  415.0  
4                  The Avengers  623.4

---

In [35]:
# Ator/Atriz com maior número de filmes
max_num_film = df.sort_values(by=['Number of Movies'], ascending=False).iloc[0]

In [36]:
max_num_film

Actor                   Robert DeNiro
Total Gross                    3081.3
Number of Movies                   79
Average per Movie                39.0
#1 Movie             Meet the Fockers
Gross                           279.3
Name: 19, dtype: object

In [37]:
print(f"O(A) Ator(atriz) com o maior número de filmes é {max_num_film['Actor']}, com {max_num_film['Number of Movies']} filmes.")

O(A) Ator(atriz) com o maior número de filmes é Robert DeNiro, com 79 filmes.


In [38]:
# A média do número de filmes.
print(f"A média de filmes por ator/atriz é de {df['Number of Movies'].mean()}")

A média de filmes por ator/atriz é de 37.88


In [39]:
# O ator/atriz com a maior média por filme
max_mean_film = df.sort_values(by=['Average per Movie'], ascending=False).iloc[0]
print(f"O(A) ator(atriz) com a maior média por filme é {max_mean_film['Actor']}, com {max_mean_film['Average per Movie']}")

O(A) ator(atriz) com a maior média por filme é Anthony Daniels, com 451.8


In [40]:
# O nome do(s) filme(s) mais frequente(s) e sua respectiva frequência.
movie_freq = df.groupby(['#1 Movie']).count().sort_values(by=['Average per Movie'], ascending=False)
max_freq = movie_freq.iloc[0]['Average per Movie']

In [41]:
most_freq_film = movie_freq.loc[movie_freq['Average per Movie'] == max_freq]

In [42]:
print("Filme(s) mais frequente(s)")
for f in most_freq_film.iterrows():
    print(f"- {f[0]} com um total de {max_freq} aparições")

Filme(s) mais frequente(s)
- The Avengers com um total de 6 aparições
